from setuptools import setup, find_packages

setup(
    name='havarti',
    version='1.0',
    description='A quaint cheese shop that plays nicely in The Cloud.',
    author='Jake Basile',
    url='http://www.jakebasile.com/projects/havarti/',
    download_url='http://www.jakebasile.com/downloads/havarti-1.0.tar.gz',
    packages=find_packages(),
    include_package_data=True,
    install_requires=[
        'Flask==0.9',
        'Jinja2==2.6',
        'SQLAlchemy==0.8.0b2',
        'Werkzeug==0.8.3',
        'amqp==1.0.6',
        'anyjson==0.3.3',
        'billiard==2.7.3.19',
        'boto==2.7.0',
        'celery==3.0.13',
        'distribute==0.6.31',
        'kombu==2.5.4',
        'python-cloudfiles==1.7.10',
        'python-dateutil==1.5',
        'redis==2.7.2',
        'requests==1.1.0',
        'wsgiref==0.1.2',
        'beautifulsoup4==4.1.3',
        'psycopg2==2.4.6',
    ],
)
