from setuptools import setup, find_packages

setup(
    name='havarti',
    version='0.4',
    description='A quaint cheese shop that plays nicely in The Cloud.',
    author='Jake Basile',
    url='http://www.jakebasile.com/projects/havarti/',
    download_url='http://www.jakebasile.com/downloads/havarti-0.4.tar.gz',
    packages=find_packages(),
    include_package_data=True,
    install_requires=[
        ['Flask==0.9'],
        ['Flask-PyMongo==0.1.2'],
        ['Jinja2==2.6'],
        ['Werkzeug==0.8.3'],
        ['amqplib==1.0.2'],
        ['anyjson==0.3.3'],
        ['beautifulsoup4==4.1.1'],
        ['billiard==2.7.3.12'],
        ['boto==2.5.2'],
        ['celery==3.0.9'],
        ['celery-with-mongodb==3.0'],
        ['distribute==0.6.24'],
        ['kombu==2.4.5'],
        ['pymongo==2.3'],
        ['python-cloudfiles==1.7.10'],
        ['python-dateutil==1.5'],
        ['requests==0.14.0'],
    ],
)
